<?php

namespace Damoon\Custom\Route;

use Illuminate\Support\Str;

class Route extends \Illuminate\Support\Facades\Route
{
    public static function post(string $uri, callable|array|string|null $action = null): \Illuminate\Routing\Route
    {
        $uri = Str::finish($uri, '/');
        return parent::post($uri, $action); // TODO: Change the autogenerated stub
    }

    public static function put(string $uri, callable|array|string|null $action = null): \Illuminate\Routing\Route
    {
        $uri = Str::finish($uri, '/');
        return parent::put($uri, $action); // TODO: Change the autogenerated stub
    }

    public static function get(string $uri, callable|array|string|null $action = null): \Illuminate\Routing\Route
    {
        $uri = Str::finish($uri, '/');
        return parent::get($uri, $action); // TODO: Change the autogenerated stub
    }

    public static function delete(string $uri, callable|array|string|null $action = null): \Illuminate\Routing\Route
    {
        $uri = Str::finish($uri, '/');
        return parent::delete($uri, $action); // TODO: Change the autogenerated stub
    }

    public static function patch(string $uri, callable|array|string|null $action = null): \Illuminate\Routing\Route
    {
        $uri = Str::finish($uri, '/');
        return parent::patch($uri, $action); // TODO: Change the autogenerated stub
    }
}
